# Generated by Django 4.2 on 2023-06-27 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_image',
            field=models.ImageField(default='blank.png', upload_to='user_images'),
        ),
    ]
