# Generated by Django 4.2 on 2023-06-28 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_likepost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikePost',
        ),
    ]
