# Generated by Django 4.2 on 2023-06-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default=None, upload_to='newpost_images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user_image',
            field=models.ImageField(upload_to='post_images'),
        ),
    ]
