# Generated by Django 4.2 on 2023-06-30 11:36

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_post_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='misPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('user_image', models.ImageField(upload_to='post_images')),
                ('image', models.ImageField(default=None, upload_to='user_images')),
                ('caption', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('no_of_likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='post',
        ),
    ]
