# Generated by Django 4.2 on 2023-06-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_mispost_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mispost',
            name='image',
            field=models.ImageField(default=None, upload_to='post_images'),
        ),
        migrations.AlterField(
            model_name='mispost',
            name='user_image',
            field=models.ImageField(upload_to='user_images'),
        ),
    ]
