# Generated by Django 4.2 on 2023-07-04 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_followercount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Post1',
        ),
    ]
