# Generated by Django 4.2 on 2023-07-04 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
